homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 44.808026
  longitude: -0.262295
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 57
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Weather prediction
sensor:
  - platform: yweather
    name: Today 
    monitored_conditions:
      - weather
      - temperature
      - temp_min
      - temp_max
  - platform: yweather
    forecast: 1
    name: Tomorrow 
    monitored_conditions:
      - weather
      - temperature
      - temp_min
      - temp_max
  - platform: google_travel_time
    name: Home to Work
    api_key: AIzaSyDGmDWjFqwoZAiw4rrNxw3iu5Cdq3kX8M4
    origin: 24 Gombaud Espiet, France
    destination: 22 quai de Bacalan Bordeaux, France
    options:
      departure_time: now
  - platform: google_travel_time
    name: Work to Home
    api_key: AIzaSyDGmDWjFqwoZAiw4rrNxw3iu5Cdq3kX8M4
    origin:  22 Quai de Bacalan Bordeaux, France
    destination: 24 Gombaud Espiet, France
    options:
      departure_time: now

# Text to speech
tts:
  - platform: google
    language: 'fr'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

media_player:
  - platform: kodi
    host: 192.168.1.19

device_tracker:
  - platform: nmap_tracker
    interval_seconds: 60
    hosts: 192.168.1.1-30
